#pragma once

#include "${CMAKE_CURRENT_LIST_DIR}/ArcFileNames.h"

#define INFOCELL_ARC1_DATA_PATH "${INFOCELL_ARC1_DATA_PATH}"
#define INFOCELL_ARC2_DATA_PATH "${INFOCELL_ARC2_DATA_PATH}"
#define INFOCELL_ORIGARC_FILEPATH "${INFOCELL_ARC_TRAINING_PATH}"
#define INFOCELL_ARCPRIZE_PATH "${INFOCELL_ARC_PRIZE_PATH}"
