add_subdirectory(printers)
add_subdirectory(tests)

add_library(cells-lib STATIC
    Ast.cc
    Ast.h
    AstImpl.h
    Cells.cc
    Cells.h
    Compiler.cc
    Compiler.h
    IDs.cc
    IDs.h
    Library.cc
    Library.h
    NodeBase.cc
    NodeBase.h
    Op.cc
    Op.h
    OpActivator.cc
    OpActivator.h
    StdLib.cc
    StdLib.h
    ToolFinder.cc
    ToolFinder.h
    World.cc
    World.h
    Cells.natvis
)
target_include_directories(cells-lib
    PUBLIC
        ${PROJECT_SOURCE_DIR}/include
        ${PROJECT_SOURCE_DIR}/src
)
target_compile_definitions(cells-lib
    PRIVATE
        $<$<CONFIG:Release>:NDEBUG>
)
target_link_libraries(cells-lib
    PUBLIC
        fmt::fmt
        spdlog::spdlog
        utf8cpp
        cells-printers
        util
)