#include "IDs.h"
#include "World.h"

namespace infocell {
namespace cells {

ID::Direction::Direction(World& w) :
    up(w, w.std.Char, "up"),
    down(w, w.std.Char, "down"),
    left(w, w.std.Char, "left"),
    right(w, w.std.Char, "right")
{
}

ID::Coordinates::Coordinates(World& w) :
    x(w, w.std.Char, "x"),
    y(w, w.std.Char, "y")
{
}

ID::ID(World& w) :
    w(w),
    directions(w),
    coordinates(w),
    __type__(w, w.std.Char, "__type__"),
    argument(w, w.std.Char, "argument"),
    ast(w, w.std.Char, "ast"),
    asts(w, w.std.Char, "asts"),
    blue(w, w.std.Char, "blue"),
    break_(w, w.std.Char, "break_"),
    cell(w, w.std.Char, "cell"),
    children(w, w.std.Char, "children"),
    color(w, w.std.Char, "color"),
    compiled(w, w.std.Char, "compiled"),
    condition(w, w.std.Char, "condition"),
    constructor(w, w.std.Char, "constructor"),
    container(w, w.std.Char, "container"),
    continue_(w, w.std.Char, "continue_"),
    currentFn(w, w.std.Char, "currentFn"),
    currentParam(w, w.std.Char, "currentParam"),
    currentStruct(w, w.std.Char, "currentStruct"),
    data(w, w.std.Char, "data"),
    description(w, w.std.Char, "description"),
    destructor(w, w.std.Char, "destructor"),
    else_(w, w.std.Char, "else_"),
    emptyObject(w, w.std.Char, "emptyObject"),
    enum_(w, w.std.Char, "enum_"),
    first(w, w.std.Char, "first"),
    functions(w, w.std.Char, "functions"),
    globalScope(w, w.std.Char, "globalScope"),
    green(w, w.std.Char, "green"),
    height(w, w.std.Char, "height"),
    id(w, w.std.Char, "id"),
    index(w, w.std.Char, "index"),
    input(w, w.std.Char, "input"),
    instances(w, w.std.Char, "instances"),
    instructions(w, w.std.Char, "instructions"),
    key(w, w.std.Char, "key"),
    keyType(w, w.std.Char, "keyType"),
    last(w, w.std.Char, "last"),
    lastOp(w, w.std.Char, "lastOp"),
    lhs(w, w.std.Char, "lhs"),
    list(w, w.std.Char, "list"),
    listType(w, w.std.Char, "listType"),
    localVars(w, w.std.Char, "localVars"),
    memberOf(w, w.std.Char, "memberOf"),
    members(w, w.std.Char, "members"),
    method(w, w.std.Char, "method"),
    methods(w, w.std.Char, "methods"),
    name(w, w.std.Char, "name"),
    next(w, w.std.Char, "next"),
    node(w, w.std.Char, "node"),
    nodeType(w, w.std.Char, "nodeType"),
    objectType(w, w.std.Char, "objectType"),
    op(w, w.std.Char, "op"),
    ops(w, w.std.Char, "ops"),
    output(w, w.std.Char, "output"),
    parameters(w, w.std.Char, "parameters"),
    parent(w, w.std.Char, "parent"),
    pixels(w, w.std.Char, "pixels"),
    pixelsMap(w, w.std.Char, "pixelsMap"),
    pop(w, w.std.Char, "pop"),
    previous(w, w.std.Char, "previous"),
    process(w, w.std.Char, "process"),
    push(w, w.std.Char, "push"),
    red(w, w.std.Char, "red"),
    resolvedScope(w, w.std.Char, "resolvedScope"),
    result(w, w.std.Char, "result"),
    return_(w, w.std.Char, "return_"),
    returnType(w, w.std.Char, "returnType"),
    rhs(w, w.std.Char, "rhs"),
    rootNode(w, w.std.Char, "rootNode"),
    scope(w, w.std.Char, "scope"),
    scopes(w, w.std.Char, "scopes"),
    self(w, w.std.Char, "self"),
    sign(w, w.std.Char, "sign"),
    size(w, w.std.Char, "size"),
    slots(w, w.std.Char, "slots"),
    stack(w, w.std.Char, "stack"),
    state(w, w.std.Char, "state"),
    stateCondition(w, w.std.Char, "stateCondition"),
    stateElse(w, w.std.Char, "stateElse"),
    stateLhs(w, w.std.Char, "stateLhs"),
    statement(w, w.std.Char, "statement"),
    stateParam1(w, w.std.Char, "stateParam1"),
    stateParam2(w, w.std.Char, "stateParam2"),
    stateParam3(w, w.std.Char, "stateParam3"),
    stateParamEval(w, w.std.Char, "stateParamEval"),
    stateParamInit(w, w.std.Char, "stateParamInit"),
    stateRhs(w, w.std.Char, "stateRhs"),
    stateStackCall(w, w.std.Char, "stateStackCall"),
    stateStatement(w, w.std.Char, "stateStatement"),
    stateThen(w, w.std.Char, "stateThen"),
    static_(w, w.std.Char, "static_"),
    status(w, w.std.Char, "status"),
    structs(w, w.std.Char, "structs"),
    structType(w, w.std.Char, "structType"),
    tag(w, w.std.Char, "tag"),
    templateId(w, w.std.Char, "templateId"),
    templateParams(w, w.std.Char, "templateParams"),
    then(w, w.std.Char, "then"),
    throw_(w, w.std.Char, "throw"),
    type(w, w.std.Char, "type"),
    typeAliases(w, w.std.Char, "typeAliases"),
    unknownInstances(w, w.std.Char, "unknownInstances"),
    unknownStructs(w, w.std.Char, "unknownStructs"),
    value(w, w.std.Char, "value"),
    valueType(w, w.std.Char, "valueType"),
    variable(w, w.std.Char, "variable"),
    variables(w, w.std.Char, "variables"),
    width(w, w.std.Char, "width")
{
    m_ids = {
        { &__type__, "__type__" },
        { &argument, "argument" },
        { &ast, "ast" },
        { &asts, "asts" },
        { &blue, "blue" },
        { &break_, "break_" },
        { &cell, "cell" },
        { &children, "children" },
        { &color, "color" },
        { &compiled, "compiled" },
        { &condition, "condition" },
        { &constructor, "constructor" },
        { &container, "container" },
        { &continue_, "continue_" },
        { &currentFn, "currentFn" },
        { &currentParam, "currentParam" },
        { &currentStruct, "currentStruct" },
        { &data, "data" },
        { &description, "description" },
        { &destructor, "destructor" },
        { &else_, "else_" },
        { &emptyObject, "emptyObject" },
        { &enum_, "enum_" },
        { &first, "first" },
        { &functions, "functions" },
        { &globalScope, "globalScope" },
        { &green, "green" },
        { &height, "height" },
        { &id, "id" },
        { &index, "index" },
        { &input, "input" },
        { &instances, "instances" },
        { &instructions, "instructions" },
        { &key, "key" },
        { &keyType, "keyType" },
        { &last, "last" },
        { &lastOp, "lastOp" },
        { &lhs, "lhs" },
        { &list, "list" },
        { &listType, "listType" },
        { &localVars, "localVars" },
        { &memberOf, "memberOf" },
        { &members, "members" },
        { &method, "method" },
        { &methods, "methods" },
        { &name, "name" },
        { &next, "next" },
        { &node, "node" },
        { &nodeType, "nodeType" },
        { &objectType, "objectType" },
        { &op, "op" },
        { &ops, "ops" },
        { &output, "output" },
        { &parameters, "parameters" },
        { &parent, "parent" },
        { &pixels, "pixels" },
        { &pixelsMap, "pixelsMap" },
        { &pop, "pop" },
        { &previous, "previous" },
        { &process, "process" },
        { &push, "push" },
        { &red, "red" },
        { &resolvedScope, "resolvedScope" },
        { &result, "result" },
        { &return_, "return_" },
        { &returnType, "returnType" },
        { &rhs, "rhs" },
        { &rootNode, "rootNode" },
        { &scope, "scope" },
        { &scopes, "scopes" },
        { &self, "self" },
        { &sign, "sign" },
        { &size, "size" },
        { &slots, "slots" },
        { &stack, "stack" },
        { &state, "state" },
        { &stateCondition, "stateCondition" },
        { &stateElse, "stateElse" },
        { &stateLhs, "stateLhs" },
        { &statement, "statement" },
        { &stateParam1, "stateParam1" },
        { &stateParam2, "stateParam2" },
        { &stateParam3, "stateParam3" },
        { &stateParamEval, "stateParamEval" },
        { &stateParamInit, "stateParamInit" },
        { &stateRhs, "stateRhs" },
        { &stateStackCall, "stateStackCall" },
        { &stateStatement, "stateStatement" },
        { &stateThen, "stateThen" },
        { &static_, "static_" },
        { &status, "status" },
        { &structs, "structs" },
        { &structType, "structType" },
        { &tag, "tag" },
        { &templateId, "templateId" },
        { &templateParams, "templateParams" },
        { &then, "then" },
        { &throw_, "throw" },
        { &type, "type" },
        { &typeAliases, "typeAliases" },
        { &unknownInstances, "unknownInstances" },
        { &unknownStructs, "unknownStructs" },
        { &value, "value" },
        { &valueType, "valueType" },
        { &variable, "variable" },
        { &variables, "variables" },
        { &width, "width" },

        { &directions.up, "up" },
        { &directions.down, "down" },
        { &directions.left, "left" },
        { &directions.right, "right" },

        { &coordinates.x, "x" },
        { &coordinates.y, "y"  }
    };
}

} // namespace cells
} // namespace infocell
