#include "IDs.h"
#include "World.h"

namespace infocell {
namespace cells {

ID::Direction::Direction(World& w) :
    up(w.name("up")),
    down(w.name("down")),
    left(w.name("left")),
    right(w.name("right"))
{
}

ID::Coordinates::Coordinates(World& w) :
    x(w.name("x")),
    y(w.name("y"))
{
}

ID::ID(World& w) :
    w(w),
    directions(w),
    coordinates(w),
    __type__(w.name("__type__")),
    argument(w.name("argument")),
    ast(w.name("ast")),
    asts(w.name("asts")),
    blue(w.name("blue")),
    break_(w.name("break_")),
    cell(w.name("cell")),
    children(w.name("children")),
    color(w.name("color")),
    compiled(w.name("compiled")),
    condition(w.name("condition")),
    constructor(w.name("constructor")),
    container(w.name("container")),
    continue_(w.name("continue_")),
    currentFn(w.name("currentFn")),
    currentParam(w.name("currentParam")),
    currentStruct(w.name("currentStruct")),
    data(w.name("data")),
    description(w.name("description")),
    destructor(w.name("destructor")),
    else_(w.name("else_")),
    emptyObject(w.name("emptyObject")),
    enum_(w.name("enum")),
    first(w.name("first")),
    functions(w.name("functions")),
    globalScope(w.name("globalScope")),
    green(w.name("green")),
    height(w.name("height")),
    id(w.name("id")),
    index(w.name("index")),
    input(w.name("input")),
    instances(w.name("instances")),
    instructions(w.name("instructions")),
    key(w.name("key")),
    keyType(w.name("keyType")),
    last(w.name("last")),
    lastOp(w.name("lastOp")),
    lhs(w.name("lhs")),
    list(w.name("list")),
    listType(w.name("listType")),
    localVars(w.name("localVars")),
    memberOf(w.name("memberOf")),
    members(w.name("members")),
    method(w.name("method")),
    methods(w.name("methods")),
    name(w.name("name")),
    next(w.name("next")),
    node(w.name("node")),
    nodeType(w.name("nodeType")),
    objectType(w.name("objectType")),
    op(w.name("op")),
    ops(w.name("ops")),
    output(w.name("output")),
    parameters(w.name("parameters")),
    parent(w.name("parent")),
    pixels(w.name("pixels")),
    pixelsMap(w.name("pixelsMap")),
    pop(w.name("pop")),
    previous(w.name("previous")),
    process(w.name("process")),
    push(w.name("push")),
    red(w.name("red")),
    resolvedScope(w.name("resolvedScope")),
    result(w.name("result")),
    return_(w.name("return_")),
    returnType(w.name("returnType")),
    rhs(w.name("rhs")),
    rootNode(w.name("rootNode")),
    scope(w.name("scope")),
    scopes(w.name("scopes")),
    self(w.name("self")),
    sign(w.name("sign")),
    size(w.name("size")),
    slots(w.name("slots")),
    stack(w.name("stack")),
    state(w.name("state")),
    stateCondition(w.name("stateCondition")),
    stateElse(w.name("stateElse")),
    stateLhs(w.name("stateLhs")),
    statement(w.name("statement")),
    stateParam1(w.name("stateParam1")),
    stateParam2(w.name("stateParam2")),
    stateParam3(w.name("stateParam3")),
    stateParamEval(w.name("stateParamEval")),
    stateParamInit(w.name("stateParamInit")),
    stateRhs(w.name("stateRhs")),
    stateStackCall(w.name("stateStackCall")),
    stateStatement(w.name("stateStatement")),
    stateThen(w.name("stateThen")),
    static_(w.name("static_")),
    status(w.name("status")),
    structs(w.name("structs")),
    structType(w.name("structType")),
    tag(w.name("tag")),
    templateId(w.name("templateId")),
    templateParams(w.name("templateParams")),
    then(w.name("then")),
    throw_(w.name("throw")),
    type(w.name("type")),
    typeAliases(w.name("typeAliases")),
    unknownInstances(w.name("unknownInstances")),
    unknownStructs(w.name("unknownStructs")),
    value(w.name("value")),
    valueType(w.name("valueType")),
    variable(w.name("variable")),
    variables(w.name("variables")),
    width(w.name("width"))
{
    // HACK: we want to use id.__type__ as early as possible so we register these IDs first, then actually continue initializing the pool
    w.pools.init();
}

} // namespace cells
} // namespace infocell
