#include "IDs.h"
#include "World.h"

namespace infocell {
namespace cells {

ID::Direction::Direction(World& w) :
    up(w.name("up")),
    down(w.name("down")),
    left(w.name("left")),
    right(w.name("right"))
{
}

ID::Coordinates::Coordinates(World& w) :
    x(w.name("x")),
    y(w.name("y"))
{
}

ID::ID(World& w) :
    w(w),
    directions(w),
    coordinates(w),
    __type__(w.name("__type__")),
    argument(w.name("argument")),
    associatedTypes(w.name("associatedTypes")),
    ast(w.name("ast")),
    asts(w.name("asts")),
    blue(w.name("blue")),
    break_(w.name("break")),
    builder(w.name("builder")),
    cases(w.name("cases")),
    cell(w.name("cell")),
    children(w.name("children")),
    color(w.name("color")),
    compiled(w.name("compiled")),
    compiledStruct(w.name("compiledStruct")),
    compiledType(w.name("compiledType")),
    consequences(w.name("consequences")),
    condition(w.name("condition")),
    constructor(w.name("constructor")),
    container(w.name("container")),
    continue_(w.name("continue")),
    currentFn(w.name("currentFn")),
    currentParam(w.name("currentParam")),
    currentStruct(w.name("currentStruct")),
    data(w.name("data")),
    description(w.name("description")),
    destructor(w.name("destructor")),
    effect(w.name("effect")),
    else_(w.name("else")),
    emptyObject(w.name("emptyObject")),
    enum_(w.name("enum")),
    enums(w.name("enums")),
    enumType(w.name("enumType")),
    first(w.name("first")),
    fullyQualifiedName(w.name("fullyQualifiedName")),
    functions(w.name("functions")),
    globalScope(w.name("globalScope")),
    green(w.name("green")),
    height(w.name("height")),
    id(w.name("id")),
    idScope(w.name("idScope")),
    incomplete(w.name("incomplete")),
    index(w.name("index")),
    input(w.name("input")),
    instanceOf(w.name("instanceOf")),
    instances(w.name("instances")),
    instructions(w.name("instructions")),
    isConstructor(w.name("isConstructor")),
    key(w.name("key")),
    keyType(w.name("keyType")),
    last(w.name("last")),
    lastOp(w.name("lastOp")),
    lhs(w.name("lhs")),
    link(w.name("link")),
    list(w.name("list")),
    listType(w.name("listType")),
    localVars(w.name("localVars")),
    memberMapping(w.name("memberMapping")),
    memberOf(w.name("memberOf")),
    members(w.name("members")),
    membership(w.name("membership")),
    method(w.name("method")),
    methods(w.name("methods")),
    name(w.name("name")),
    next(w.name("next")),
    node(w.name("node")),
    nodeType(w.name("nodeType")),
    objectType(w.name("objectType")),
    op(w.name("op")),
    ops(w.name("ops")),
    other(w.name("other")),
    output(w.name("output")),
    parameters(w.name("parameters")),
    parent(w.name("parent")),
    parentFunction(w.name("parentFunction")),
    pixels(w.name("pixels")),
    pixelsMap(w.name("pixelsMap")),
    pop(w.name("pop")),
    previous(w.name("previous")),
    primitiveTool(w.name("primitiveTool")),
    process(w.name("process")),
    prompt(w.name("prompt")),
    push(w.name("push")),
    red(w.name("red")),
    resolvedScope(w.name("resolvedScope")),
    result(w.name("result")),
    return_(w.name("return")),
    returnType(w.name("returnType")),
    rhs(w.name("rhs")),
    rootNode(w.name("rootNode")),
    scope(w.name("scope")),
    scopes(w.name("scopes")),
    self(w.name("self")),
    selfBuilders(w.name("selfBuilders")),
    sign(w.name("sign")),
    size(w.name("size")),
    slotKeyList(w.name("slotKeyList")),
    stack(w.name("stack")),
    state(w.name("state")),
    statement(w.name("statement")),
    static_(w.name("static")),
    status(w.name("status")),
    structs(w.name("structs")),
    structType(w.name("structType")),
    tag(w.name("tag")),
    templateId(w.name("templateId")),
    templateParams(w.name("templateParams")),
    then(w.name("then")),
    throw_(w.name("throw")),
    traitImpls(w.name("traitImpls")),
    type(w.name("type")),
    typeAliases(w.name("typeAliases")),
    unknownInstances(w.name("unknownInstances")),
    unknownStructs(w.name("unknownStructs")),
    value(w.name("value")),
    values(w.name("values")),
    valueType(w.name("valueType")),
    variable(w.name("variable")),
    variables(w.name("variables")),
    width(w.name("width"))
{
    // HACK: we want to use id.__type__ as early as possible so we register these IDs first, then actually continue initializing the pool
    w.pools.init();
}

} // namespace cells
} // namespace infocell
